# Generated by Django 5.0 on 2023-12-07 23:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_alter_thing_description_alter_thing_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(120)]),
        ),
    ]
